version: '3'

services:
  rocker:
    image: osmosisfoundation/rocker:latest
    ports:
      - 8787:8787
    volumes:
      - ./data:/home/rstudio
      - ./license:/opt/nm/license
    environment:
      - ROOT=TRUE
  piranajs:
    image: osmosisfoundation/piranajs:latest
    ports:
      - 8000:8000
    volumes:
      - ./license:/opt/nm/license
      - ./license:/opt/pirana/license
      - ./data:/data
    depends_on:
      - psn
  psn:
    image: osmosisfoundation/psn:latest
    volumes:
      - ./license:/opt/nm/license
      - ./data:/data
    depends_on:
      - nonmem
  nonmem:
    image: osmosisfoundation/nonmem:latest
    volumes:
      - ./license:/opt/nm/license
      - ./data:/data

